/** Catálogo recomendado de tratamientos odontológicos — 20 tratamientos
 * comunes en consultorios dentales de México, más 10 servicios
 * complementarios opcionales (nunca contados entre los 20). Es un dataset
 * ESTÁTICO de solo lectura, no una colección de Firestore: sirve como
 * plantilla para crear procedimientos reales en el catálogo de cada
 * clínica (`users/{clinicUid}/procedimientos`) — nunca se usa directo.
 *
 * Cada `codigo` es permanente: una vez publicado no se reutiliza ni se
 * cambia, porque es la clave que evita duplicados al importar el catálogo
 * más de una vez (ver `importarCatalogoRecomendado.ts`).
 *
 * Los precios NUNCA se definen aquí — cada clínica configura los suyos. */

import { especialidadesPredefinidas } from "./procedimientos";

export type UnidadFacturacion = "tratamiento" | "diente" | "cuadrante" | "arcada" | "cita";

export type RolComercial =
  | "captacion"
  | "servicio_recurrente"
  | "alto_valor"
  | "mantenimiento"
  | "potencial_seguimiento";

export const rolComercialLabel: Record<RolComercial, string> = {
  captacion: "Captación",
  servicio_recurrente: "Servicio recurrente",
  alto_valor: "Tratamiento de alto valor",
  mantenimiento: "Mantenimiento",
  potencial_seguimiento: "Potencial de seguimiento",
};

export type PlantillaProcedimiento = {
  codigo: string;
  nombre: string;
  /** Taxonomía propia del catálogo recomendado (Consulta, Preventiva...) —
   * distinta de `especialidadSugerida`, que es la que se copia al campo
   * `especialidad` del procedimiento real para reusar el agrupador ya
   * existente (`agruparPorEspecialidad`). */
  categoria: string;
  especialidadSugerida: (typeof especialidadesPredefinidas)[number];
  descripcionCorta: string;
  objetivoClinico: string;
  duracionSugeridaTexto: string;
  duracionMinutosSugerida: number;
  variantes: string[];
  unidadFacturacion: UnidadFacturacion;
  visitasEstimadas: string;
  registrosClinicosRecomendados: string[];
  /** Códigos de otras plantillas — solo orientativo, nunca automático. */
  tratamientosRelacionados: string[];
  seguimiento: string;
  notaAdmin: string;
  etiquetasComerciales: RolComercial[];
};

export const catalogoRecomendado: PlantillaProcedimiento[] = [
  {
    codigo: "CON-VAL",
    nombre: "Valoración dental integral",
    categoria: "Consulta",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Primera cita para evaluar la salud bucal general del paciente.",
    objetivoClinico: "Explorar, diagnosticar y definir un plan de tratamiento inicial.",
    duracionSugeridaTexto: "45–60 minutos",
    duracionMinutosSugerida: 60,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Historia clínica", "Odontograma inicial"],
    tratamientosRelacionados: [],
    seguimiento: "El diagnóstico se convierte en un presupuesto con el plan de tratamiento sugerido.",
    notaAdmin: "Suele ser la puerta de entrada de un paciente nuevo — vale la pena facilitar agendarla.",
    etiquetasComerciales: ["captacion"],
  },
  {
    codigo: "CON-URG",
    nombre: "Consulta de urgencia dental",
    categoria: "Consulta",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Atención de dolor, trauma o urgencia dental fuera de una cita programada.",
    objetivoClinico: "Controlar el dolor/urgencia y derivar al tratamiento definitivo.",
    duracionSugeridaTexto: "30–45 minutos",
    duracionMinutosSugerida: 45,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Nota de evolución", "Radiografía periapical si aplica"],
    tratamientosRelacionados: ["END-TRC", "CIR-EXTS"],
    seguimiento: "Frecuentemente deriva en una endodoncia o extracción según el diagnóstico.",
    notaAdmin: "Suele ser la primera vez que un paciente conoce el consultorio — buena oportunidad de captación.",
    etiquetasComerciales: ["captacion"],
  },
  {
    codigo: "PRE-LIM",
    nombre: "Limpieza dental / profilaxis",
    categoria: "Preventiva",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Remoción de placa y sarro para mantener la salud bucal.",
    objetivoClinico: "Prevenir enfermedad periodontal y detectar necesidades de tratamiento.",
    duracionSugeridaTexto: "45–60 minutos",
    duracionMinutosSugerida: 45,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "1 visita, con controles periódicos",
    registrosClinicosRecomendados: ["Nota de evolución"],
    tratamientosRelacionados: ["PRE-FLU", "PRE-SEL", "OPE-RES", "PER-RAR"],
    seguimiento: "Buen momento para detectar caries, necesidad de selladores o enfermedad periodontal.",
    notaAdmin: "Servicio de mantenimiento — funciona bien como recordatorio periódico al paciente.",
    etiquetasComerciales: ["mantenimiento", "potencial_seguimiento"],
  },
  {
    codigo: "PRE-FLU",
    nombre: "Aplicación tópica de flúor",
    categoria: "Preventiva",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Aplicación de flúor para fortalecer el esmalte dental.",
    objetivoClinico: "Prevenir caries, especialmente en pacientes de alto riesgo o pediátricos.",
    duracionSugeridaTexto: "15–20 minutos",
    duracionMinutosSugerida: 15,
    variantes: ["Barniz", "Gel"],
    unidadFacturacion: "tratamiento",
    visitasEstimadas: "1 visita, repetible cada 3–6 meses",
    registrosClinicosRecomendados: ["Nota de evolución"],
    tratamientosRelacionados: ["PRE-LIM"],
    seguimiento: "Suele combinarse con la limpieza dental de rutina.",
    notaAdmin: "Servicio breve y de bajo costo — común en pacientes pediátricos y de alto riesgo de caries.",
    etiquetasComerciales: ["mantenimiento"],
  },
  {
    codigo: "PRE-SEL",
    nombre: "Sellador de fosetas y fisuras",
    categoria: "Preventiva",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Barrera protectora en las fosetas y fisuras de molares y premolares.",
    objetivoClinico: "Prevenir caries en superficies oclusales de alto riesgo.",
    duracionSugeridaTexto: "15–30 minutos",
    duracionMinutosSugerida: 20,
    variantes: [],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Odontograma"],
    tratamientosRelacionados: ["PRE-LIM"],
    seguimiento: "Revisar periódicamente que el sellador siga íntegro.",
    notaAdmin: "Se cobra por diente — marcar cada pieza sellada en el odontograma al presupuestar.",
    etiquetasComerciales: ["mantenimiento"],
  },
  {
    codigo: "OPE-RES",
    nombre: "Restauración con resina",
    categoria: "Operatoria",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Restauración estética de una pieza dañada por caries u otra causa.",
    objetivoClinico: "Restablecer forma, función y estética de la pieza afectada.",
    duracionSugeridaTexto: "30–60 minutos",
    duracionMinutosSugerida: 45,
    variantes: ["Anterior", "Posterior", "Una superficie", "Dos superficies", "Tres o más superficies"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Odontograma"],
    tratamientosRelacionados: ["PRE-LIM"],
    seguimiento: "Revisar en controles de rutina que la restauración siga en buen estado.",
    notaAdmin: "El precio suele variar según el número de superficies — considera precios distintos por variante.",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "PER-RAR",
    nombre: "Raspado y alisado radicular",
    categoria: "Periodoncia",
    especialidadSugerida: "Periodoncia",
    descripcionCorta: "Limpieza profunda debajo de la encía para tratar enfermedad periodontal.",
    objetivoClinico: "Controlar la enfermedad periodontal y detener su progresión.",
    duracionSugeridaTexto: "45–60 minutos",
    duracionMinutosSugerida: 60,
    variantes: ["Por cuadrante", "Boca completa"],
    unidadFacturacion: "cuadrante",
    visitasEstimadas: "1–4 visitas según cuadrantes",
    registrosClinicosRecomendados: ["Periodontograma", "Nota de evolución"],
    tratamientosRelacionados: ["PRE-LIM"],
    seguimiento: "Requiere controles periodontales de mantenimiento periódicos.",
    notaAdmin: "Servicio de mayor duración — suele agendarse en varias citas por cuadrante.",
    etiquetasComerciales: ["mantenimiento", "potencial_seguimiento"],
  },
  {
    codigo: "CIR-EXTS",
    nombre: "Extracción dental simple",
    categoria: "Cirugía",
    especialidadSugerida: "Cirugía Oral y Maxilofacial",
    descripcionCorta: "Remoción de una pieza dental erupcionada, sin cirugía.",
    objetivoClinico: "Eliminar una pieza no viable o indicada para extracción.",
    duracionSugeridaTexto: "30–45 minutos",
    duracionMinutosSugerida: 30,
    variantes: ["Diente temporal", "Diente permanente", "Resto radicular"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Radiografía periapical", "Consentimiento informado"],
    tratamientosRelacionados: ["PRO-PPR", "PRO-FIJ", "PRO-PT"],
    seguimiento: "Valorar rehabilitación protésica del espacio si aplica.",
    notaAdmin: "Suele originar la necesidad de una rehabilitación protésica más adelante.",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "CIR-EXTQ",
    nombre: "Extracción quirúrgica / tercer molar",
    categoria: "Cirugía",
    especialidadSugerida: "Cirugía Oral y Maxilofacial",
    descripcionCorta: "Extracción de una pieza retenida o parcialmente retenida, con abordaje quirúrgico.",
    objetivoClinico: "Remover una pieza no accesible por vía simple, típicamente un tercer molar.",
    duracionSugeridaTexto: "60–90 minutos",
    duracionMinutosSugerida: 75,
    variantes: ["Erupcionado", "Parcialmente retenido", "Retenido"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita + revisión postoperatoria",
    registrosClinicosRecomendados: ["Radiografía panorámica", "Consentimiento informado"],
    tratamientosRelacionados: [],
    seguimiento: "Revisión postoperatoria y retiro de sutura si aplica.",
    notaAdmin: "Procedimiento quirúrgico de mayor complejidad y duración.",
    etiquetasComerciales: ["alto_valor", "potencial_seguimiento"],
  },
  {
    codigo: "END-TRC",
    nombre: "Endodoncia",
    categoria: "Endodoncia",
    especialidadSugerida: "Endodoncia",
    descripcionCorta: "Tratamiento de conductos para salvar una pieza con daño pulpar.",
    objetivoClinico: "Eliminar la infección/inflamación pulpar y conservar la pieza dental.",
    duracionSugeridaTexto: "60–120 minutos",
    duracionMinutosSugerida: 90,
    variantes: ["Anterior", "Premolar", "Molar", "Retratamiento"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1–2 visitas",
    registrosClinicosRecomendados: ["Radiografía periapical", "Pruebas de vitalidad pulpar"],
    tratamientosRelacionados: ["END-REC"],
    seguimiento: "La pieza tratada suele requerir reconstrucción postendodóncica y, después, una corona.",
    notaAdmin: "Tratamiento de alto valor — conviene presupuestar junto con la reconstrucción posterior.",
    etiquetasComerciales: ["alto_valor", "potencial_seguimiento"],
  },
  {
    codigo: "END-REC",
    nombre: "Reconstrucción postendodóncica",
    categoria: "Endodoncia",
    especialidadSugerida: "Endodoncia",
    descripcionCorta: "Reconstrucción de la pieza después de una endodoncia, previa a la corona definitiva.",
    objetivoClinico: "Dar soporte estructural a la pieza tratada antes de rehabilitarla.",
    duracionSugeridaTexto: "30–60 minutos",
    duracionMinutosSugerida: 45,
    variantes: ["Reconstrucción con resina", "Muñón", "Poste de fibra"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Radiografía periapical"],
    tratamientosRelacionados: ["END-TRC", "PRO-FIJ"],
    seguimiento: "Normalmente continúa con una corona (prótesis fija).",
    notaAdmin: "Paso intermedio casi siempre necesario entre la endodoncia y la corona definitiva.",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "PRO-FIJ",
    nombre: "Prótesis fija",
    categoria: "Prótesis",
    especialidadSugerida: "Prótesis",
    descripcionCorta: "Incrustación, corona o puente cementados de forma permanente.",
    objetivoClinico: "Restaurar forma, función y estética de una o más piezas de forma fija.",
    duracionSugeridaTexto: "Tratamiento de varias citas",
    duracionMinutosSugerida: 60,
    variantes: [
      "Incrustación",
      "Corona",
      "Puente",
      "Zirconia",
      "Disilicato de litio",
      "Metal-porcelana",
    ],
    unidadFacturacion: "diente",
    visitasEstimadas: "2–3 visitas",
    registrosClinicosRecomendados: ["Radiografía periapical", "Impresión/escaneo digital"],
    tratamientosRelacionados: ["END-REC", "CIR-EXTS"],
    seguimiento: "Revisar ajuste y oclusión en controles posteriores a la cementación.",
    notaAdmin: "Tratamiento de alto valor — el precio varía mucho según el material elegido.",
    etiquetasComerciales: ["alto_valor"],
  },
  {
    codigo: "PRO-PPR",
    nombre: "Prótesis parcial removible",
    categoria: "Prótesis",
    especialidadSugerida: "Prótesis",
    descripcionCorta: "Prótesis removible que rehabilita varias piezas ausentes.",
    objetivoClinico: "Restaurar función masticatoria y estética en pacientes parcialmente edéntulos.",
    duracionSugeridaTexto: "Tratamiento de varias citas",
    duracionMinutosSugerida: 60,
    variantes: ["Acrílica", "Flexible", "Metálica", "Superior", "Inferior"],
    unidadFacturacion: "arcada",
    visitasEstimadas: "3–5 visitas",
    registrosClinicosRecomendados: ["Impresión/escaneo digital", "Registro de mordida"],
    tratamientosRelacionados: ["CIR-EXTS"],
    seguimiento: "Ajustes periódicos y revisión de tejidos de soporte.",
    notaAdmin: "Tratamiento de alto valor con varias citas de laboratorio.",
    etiquetasComerciales: ["alto_valor"],
  },
  {
    codigo: "PRO-PT",
    nombre: "Prótesis total",
    categoria: "Prótesis",
    especialidadSugerida: "Prótesis",
    descripcionCorta: "Prótesis removible completa para arcadas totalmente edéntulas.",
    objetivoClinico: "Restaurar función y estética en un paciente sin dientes naturales en la arcada.",
    duracionSugeridaTexto: "Tratamiento de varias citas",
    duracionMinutosSugerida: 60,
    variantes: ["Superior", "Inferior", "Ambas arcadas"],
    unidadFacturacion: "arcada",
    visitasEstimadas: "4–6 visitas",
    registrosClinicosRecomendados: ["Impresión/escaneo digital", "Registro de mordida"],
    tratamientosRelacionados: ["CIR-EXTS"],
    seguimiento: "Ajustes periódicos y revisión de tejidos de soporte.",
    notaAdmin: "Tratamiento de alto valor — considera precio distinto por una o ambas arcadas.",
    etiquetasComerciales: ["alto_valor"],
  },
  {
    codigo: "ORT-INI",
    nombre: "Inicio de tratamiento de ortodoncia",
    categoria: "Ortodoncia",
    especialidadSugerida: "Ortodoncia",
    descripcionCorta: "Colocación de aparatología para iniciar el tratamiento de ortodoncia.",
    objetivoClinico: "Alinear la dentición y corregir la oclusión a lo largo del tratamiento.",
    duracionSugeridaTexto: "60–120 minutos",
    duracionMinutosSugerida: 90,
    variantes: ["Brackets convencionales", "Brackets autoligado", "Una arcada", "Dos arcadas"],
    unidadFacturacion: "tratamiento",
    visitasEstimadas: "Tratamiento largo, con controles mensuales",
    registrosClinicosRecomendados: ["Radiografía panorámica", "Fotografías clínicas", "Impresión/escaneo digital"],
    tratamientosRelacionados: ["ORT-CTL"],
    seguimiento: "Continúa con controles mensuales hasta terminar el tratamiento activo.",
    notaAdmin: "Tratamiento de alto valor que genera ingresos recurrentes por los controles mensuales.",
    etiquetasComerciales: ["alto_valor", "servicio_recurrente"],
  },
  {
    codigo: "ORT-CTL",
    nombre: "Control de ortodoncia",
    categoria: "Ortodoncia",
    especialidadSugerida: "Ortodoncia",
    descripcionCorta: "Cita periódica de ajuste durante un tratamiento de ortodoncia activo.",
    objetivoClinico: "Dar seguimiento y ajustar la aparatología durante el tratamiento.",
    duracionSugeridaTexto: "20–30 minutos",
    duracionMinutosSugerida: 20,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "Mensual durante todo el tratamiento",
    registrosClinicosRecomendados: ["Nota de evolución"],
    tratamientosRelacionados: ["ORT-INI"],
    seguimiento: "Al concluir el tratamiento activo, continúa con retenedores.",
    notaAdmin: "Servicio recurrente — es el ingreso mensual asociado a cada paciente de ortodoncia activo.",
    etiquetasComerciales: ["servicio_recurrente"],
  },
  {
    codigo: "EST-BLA",
    nombre: "Blanqueamiento dental",
    categoria: "Estética",
    especialidadSugerida: "Estética Dental",
    descripcionCorta: "Aclaramiento del color dental con fines estéticos.",
    objetivoClinico: "Mejorar la estética dental del paciente.",
    duracionSugeridaTexto: "60–90 minutos",
    duracionMinutosSugerida: 60,
    variantes: ["En consultorio", "Ambulatorio (para casa)", "Combinado"],
    unidadFacturacion: "tratamiento",
    visitasEstimadas: "1–2 visitas",
    registrosClinicosRecomendados: ["Fotografías clínicas", "Valoración previa de caries/restauraciones"],
    tratamientosRelacionados: [],
    seguimiento: "Recomendar mantenimiento periódico según el hábito del paciente.",
    notaAdmin: "Tratamiento electivo de alto valor percibido por el paciente.",
    etiquetasComerciales: ["alto_valor"],
  },
  {
    codigo: "OCL-GUA",
    nombre: "Guarda oclusal",
    categoria: "Oclusión",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Dispositivo removible para proteger los dientes del bruxismo o problemas oclusales.",
    objetivoClinico: "Proteger la dentición y estabilizar la oclusión.",
    duracionSugeridaTexto: "Varias citas",
    duracionMinutosSugerida: 30,
    variantes: ["Blanda", "Rígida", "Estabilizadora"],
    unidadFacturacion: "arcada",
    visitasEstimadas: "2 visitas (toma de impresión y entrega)",
    registrosClinicosRecomendados: ["Impresión/escaneo digital"],
    tratamientosRelacionados: [],
    seguimiento: "Revisar ajuste y desgaste en controles periódicos.",
    notaAdmin: "Requiere laboratorio — considera el tiempo de entrega al agendar la segunda cita.",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "ODP-PUL",
    nombre: "Terapia pulpar pediátrica",
    categoria: "Odontopediatría",
    especialidadSugerida: "Odontopediatría",
    descripcionCorta: "Tratamiento de la pulpa de un diente temporal afectado.",
    objetivoClinico: "Conservar el diente temporal hasta su exfoliación natural.",
    duracionSugeridaTexto: "45–60 minutos",
    duracionMinutosSugerida: 45,
    variantes: ["Pulpotomía", "Pulpectomía"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Radiografía periapical"],
    tratamientosRelacionados: ["ODP-COR"],
    seguimiento: "Casi siempre continúa con una corona pediátrica.",
    notaAdmin: "Requiere manejo de conducta apropiado para el paciente pediátrico.",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "ODP-COR",
    nombre: "Corona pediátrica",
    categoria: "Odontopediatría",
    especialidadSugerida: "Odontopediatría",
    descripcionCorta: "Restauración de cobertura total para un diente temporal.",
    objetivoClinico: "Proteger y restaurar un diente temporal con daño extenso.",
    duracionSugeridaTexto: "45–60 minutos",
    duracionMinutosSugerida: 45,
    variantes: ["Acero-cromo", "Estética"],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Radiografía periapical"],
    tratamientosRelacionados: ["ODP-PUL"],
    seguimiento: "Revisar en controles pediátricos de rutina.",
    notaAdmin: "Suele seguir a una terapia pulpar pediátrica.",
    etiquetasComerciales: ["alto_valor"],
  },
];

/** Servicios complementarios opcionales — NUNCA se cuentan entre los 20
 * tratamientos principales ni se siembran automáticamente en clínicas
 * nuevas; solo están disponibles a través del importador. */
export const serviciosComplementarios: PlantillaProcedimiento[] = [
  {
    codigo: "RAD-PER",
    nombre: "Radiografía periapical",
    categoria: "Servicio complementario",
    especialidadSugerida: "Radiología",
    descripcionCorta: "Radiografía de una o pocas piezas dentales.",
    objetivoClinico: "Apoyar el diagnóstico de una pieza o zona específica.",
    duracionSugeridaTexto: "5–10 minutos",
    duracionMinutosSugerida: 10,
    variantes: [],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: [],
    tratamientosRelacionados: ["CON-URG", "END-TRC", "CIR-EXTS"],
    seguimiento: "Se usa para apoyar el diagnóstico de otros tratamientos.",
    notaAdmin: "Servicio de apoyo diagnóstico, de duración muy breve.",
    etiquetasComerciales: [],
  },
  {
    codigo: "CON-SUB",
    nombre: "Consulta subsecuente",
    categoria: "Servicio complementario",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Cita de seguimiento a un tratamiento ya iniciado.",
    objetivoClinico: "Dar seguimiento a la evolución del paciente.",
    duracionSugeridaTexto: "20–30 minutos",
    duracionMinutosSugerida: 20,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "Según el caso",
    registrosClinicosRecomendados: ["Nota de evolución"],
    tratamientosRelacionados: [],
    seguimiento: "",
    notaAdmin: "Útil para no tener que reutilizar el precio de la valoración inicial en cada visita.",
    etiquetasComerciales: ["servicio_recurrente"],
  },
  {
    codigo: "OPE-PRO",
    nombre: "Curación o restauración provisional",
    categoria: "Servicio complementario",
    especialidadSugerida: "Odontología General",
    descripcionCorta: "Restauración temporal mientras se realiza el tratamiento definitivo.",
    objetivoClinico: "Proteger la pieza mientras se programa el tratamiento definitivo.",
    duracionSugeridaTexto: "20–30 minutos",
    duracionMinutosSugerida: 20,
    variantes: [],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: [],
    tratamientosRelacionados: ["OPE-RES", "END-TRC"],
    seguimiento: "Debe sustituirse por el tratamiento definitivo.",
    notaAdmin: "",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "PRO-REC",
    nombre: "Recementado de corona",
    categoria: "Servicio complementario",
    especialidadSugerida: "Prótesis",
    descripcionCorta: "Recementar una corona que se despegó.",
    objetivoClinico: "Reponer la fijación de una prótesis fija existente.",
    duracionSugeridaTexto: "20–30 minutos",
    duracionMinutosSugerida: 20,
    variantes: [],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: [],
    tratamientosRelacionados: ["PRO-FIJ"],
    seguimiento: "",
    notaAdmin: "",
    etiquetasComerciales: [],
  },
  {
    codigo: "PRO-REP",
    nombre: "Reparación de prótesis",
    categoria: "Servicio complementario",
    especialidadSugerida: "Prótesis",
    descripcionCorta: "Reparación de una prótesis removible dañada o fracturada.",
    objetivoClinico: "Restaurar la función de una prótesis existente sin rehacerla.",
    duracionSugeridaTexto: "30–45 minutos",
    duracionMinutosSugerida: 30,
    variantes: [],
    unidadFacturacion: "tratamiento",
    visitasEstimadas: "1–2 visitas",
    registrosClinicosRecomendados: [],
    tratamientosRelacionados: ["PRO-PPR", "PRO-PT"],
    seguimiento: "",
    notaAdmin: "",
    etiquetasComerciales: [],
  },
  {
    codigo: "CIR-SUT",
    nombre: "Retiro de sutura",
    categoria: "Servicio complementario",
    especialidadSugerida: "Cirugía Oral y Maxilofacial",
    descripcionCorta: "Retiro de puntos de sutura tras un procedimiento quirúrgico.",
    objetivoClinico: "Completar el postoperatorio de una cirugía previa.",
    duracionSugeridaTexto: "10–15 minutos",
    duracionMinutosSugerida: 15,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: [],
    tratamientosRelacionados: ["CIR-EXTQ"],
    seguimiento: "",
    notaAdmin: "",
    etiquetasComerciales: [],
  },
  {
    codigo: "ORT-BRA",
    nombre: "Bracket despegado",
    categoria: "Servicio complementario",
    especialidadSugerida: "Ortodoncia",
    descripcionCorta: "Recolocación de un bracket que se despegó durante el tratamiento.",
    objetivoClinico: "Mantener la aparatología de ortodoncia en buen estado.",
    duracionSugeridaTexto: "15–20 minutos",
    duracionMinutosSugerida: 15,
    variantes: [],
    unidadFacturacion: "diente",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: [],
    tratamientosRelacionados: ["ORT-INI", "ORT-CTL"],
    seguimiento: "",
    notaAdmin: "",
    etiquetasComerciales: [],
  },
  {
    codigo: "ORT-RET",
    nombre: "Retenedores de ortodoncia",
    categoria: "Servicio complementario",
    especialidadSugerida: "Ortodoncia",
    descripcionCorta: "Entrega de retenedores al concluir el tratamiento activo de ortodoncia.",
    objetivoClinico: "Mantener el resultado del tratamiento de ortodoncia a largo plazo.",
    duracionSugeridaTexto: "20–30 minutos",
    duracionMinutosSugerida: 20,
    variantes: ["Fijo", "Removible"],
    unidadFacturacion: "arcada",
    visitasEstimadas: "1–2 visitas",
    registrosClinicosRecomendados: ["Impresión/escaneo digital"],
    tratamientosRelacionados: ["ORT-INI", "ORT-CTL"],
    seguimiento: "Revisar en controles periódicos de rutina.",
    notaAdmin: "",
    etiquetasComerciales: ["potencial_seguimiento"],
  },
  {
    codigo: "ODP-MES",
    nombre: "Mantenedor de espacio",
    categoria: "Servicio complementario",
    especialidadSugerida: "Odontopediatría",
    descripcionCorta: "Dispositivo para conservar el espacio de un diente temporal perdido prematuramente.",
    objetivoClinico: "Prevenir problemas de erupción del diente permanente.",
    duracionSugeridaTexto: "30–45 minutos",
    duracionMinutosSugerida: 30,
    variantes: ["Fijo", "Removible"],
    unidadFacturacion: "diente",
    visitasEstimadas: "2 visitas",
    registrosClinicosRecomendados: ["Radiografía periapical"],
    tratamientosRelacionados: ["CIR-EXTS"],
    seguimiento: "Revisar en controles pediátricos de rutina.",
    notaAdmin: "",
    etiquetasComerciales: [],
  },
  {
    codigo: "CIR-SEG",
    nombre: "Seguimiento postoperatorio",
    categoria: "Servicio complementario",
    especialidadSugerida: "Cirugía Oral y Maxilofacial",
    descripcionCorta: "Cita de revisión posterior a un procedimiento quirúrgico.",
    objetivoClinico: "Verificar una cicatrización adecuada.",
    duracionSugeridaTexto: "15–20 minutos",
    duracionMinutosSugerida: 15,
    variantes: [],
    unidadFacturacion: "cita",
    visitasEstimadas: "1 visita",
    registrosClinicosRecomendados: ["Nota de evolución"],
    tratamientosRelacionados: ["CIR-EXTQ"],
    seguimiento: "",
    notaAdmin: "",
    etiquetasComerciales: [],
  },
];

export function buscarPlantillaPorCodigo(codigo: string | undefined): PlantillaProcedimiento | undefined {
  if (!codigo) return undefined;
  return (
    catalogoRecomendado.find((p) => p.codigo === codigo) ??
    serviciosComplementarios.find((p) => p.codigo === codigo)
  );
}
